name: CI
permissions:
  contents: read
jobs:
  test:
    uses: json-schema-tools/foundation/.github/workflows/node-ci.yml@66e2ac8fb6a5f53bbd4f1a34468e14ea7c9333a8
    with:
      lint-command: npm run lint -- --no-fix
      build-command: npm run build
      test-command: npm test -- --runInBand
  commitlint:
    uses: json-schema-tools/foundation/.github/workflows/commitlint.yml@66e2ac8fb6a5f53bbd4f1a34468e14ea7c9333a8
    permissions:
      contents: read
      pull-requests: read
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch: null
